server.name: apm-server
server.host: 0.0.0.0

output.elasticsearch:
  hosts: [ http://elasticsearch:9200 ]
  protocol: "http"
  username: "elastic"
  password: "${ELASTIC_PASSWORD}"

setup.kibana:
  host: "http://kibana:5601"
  username: "kibana_system"
  password: "${KIBANA_SYSTEM_PASSWORD}"

